<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Permasalahan_model extends CI_Model
{

    public $table = 'permasalahan';
    public $id = 'id_masalah';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
        $this->db3 = $this->load->database('db3',TRUE);
    }

    // get all
    function get_all($status)
    {
      $this->db3->select('m.*, k.*, s.*');
      $this->db3->from('permasalahan m');
      $this->db3->join('kegiatan k','k.id_kegiatan=m.kegiatan','left');
      $this->db3->join('epiz_21636198_simolek.skpd s','s.id_skpd=k.skpd','left');
      if ($status <> null){
        $this->db3->where('m.status',$status);
      };
      $this->db3->order_by('m.status', 'asc');
      $this->db3->order_by('m.sejak', 'desc');
      return $this->db3->get()->result();
    }

    // get perkegiatan
    function get_perkegiatan($id)
    {
        $this->db3->where('kegiatan',$id);
        $this->db3->order_by($this->id, $this->order);
        return $this->db3->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db3->where($this->id, $id);
        return $this->db3->get($this->table)->row();
    }

    // insert data
    function insert($data)
    {
        $this->db3->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db3->where($this->id, $id);
        $this->db3->update($this->table, $data);
    }

    // update data
    function input_solusi($id, $data)
    {
        $this->db3->set('solusi',$data['solusi']);
        $this->db3->set('status',$data['status']);
        $this->db3->set('selesai',$data['selesai']);
        $this->db3->where($this->id, $id);
        $this->db3->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db3->where($this->id, $id);
        $this->db3->delete($this->table);
    }

}

/* End of file Permasalahan_model.php */
/* Location: ./application/models/Permasalahan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-11-26 14:40:23 */
/* http://harviacode.com */
